# Generated by Django 4.0.8 on 2023-01-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='abcdef', max_length=250, unique=True),
        ),
    ]
