# Generated by Django 4.0.8 on 2023-01-31 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-update', '-create']},
        ),
        migrations.AddField(
            model_name='book',
            name='create',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='book',
            name='update',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
