# Generated by Django 4.0.8 on 2023-01-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_book_options_book_create_book_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
