# Generated by Django 4.0.8 on 2023-02-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_create',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
