# Generated by Django 4.0.8 on 2023-02-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='public_or_private',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(default='Unknow', max_length=200),
        ),
    ]
