# Generated by Django 5.0.3 on 2024-04-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_book_public_or_private_book_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(max_length=200),
        ),
    ]
